# Generated by Django 4.1.7 on 2023-06-20 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('num', models.IntegerField(primary_key=True, serialize=False, verbose_name='numero de sala')),
                ('descripcion', models.CharField(max_length=50, verbose_name='Descripción')),
                ('disponible', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('rut', models.CharField(max_length=9, primary_key=True, serialize=False, verbose_name='rut')),
                ('nombre', models.CharField(max_length=50, verbose_name='nombre')),
                ('apellidos', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('correo', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('contraseña', models.CharField(max_length=18, verbose_name='contraseña')),
                ('bloqueado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.CharField(default='', max_length=4, primary_key=True, serialize=False, verbose_name='ID horario')),
                ('fecha', models.DateField()),
                ('hora_desde', models.TimeField()),
                ('hora_hasta', models.TimeField()),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sala', verbose_name='Numero de sala')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usuario', verbose_name='Usuario:')),
            ],
        ),
    ]
