# Generated by Django 4.1.7 on 2023-06-21 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='apellidos',
            field=models.CharField(default='apellido', max_length=50, verbose_name='apellido'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='contraseña',
            field=models.CharField(default='sincontraseña', max_length=50, verbose_name='contraseña'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='contraseña2',
            field=models.CharField(default='sincontraseña', max_length=50, verbose_name='contraseña'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
    ]
